In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr1 = np.array([1,2,3,4], np.int8)

In [5]:
arr1

array([1, 2, 3, 4], dtype=int8)

In [6]:
arr1[0]

1

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

1

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr1.dtype

dtype('int8')

In [11]:
arr1.shape

(4,)

In [12]:
arr1.itemsize

1

In [13]:
arr.size * arr.itemsize

16

In [14]:
arr.nbytes

16

In [15]:
arr2 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arr2)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [16]:
arr2.ndim


2

In [17]:
arr2.shape

(2, 6)

In [18]:
arr2[0,:]

array([1, 2, 3, 4, 5, 6])

In [19]:
arr2[:,2]

array([3, 3])

In [20]:
arr2[0,1:6:2]

array([2, 4, 6])

In [21]:
arr2[:,2] = 7

In [22]:
print(arr2)

[[1 2 7 4 5 6]
 [1 2 7 4 5 6]]


In [23]:
arr2[:,1]= [45,67]

In [24]:
arr2

array([[ 1, 45,  7,  4,  5,  6],
       [ 1, 67,  7,  4,  5,  6]])

In [25]:
arr3 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
print(arr3[0,2,1])

6


In [27]:
arr3[:,1,0]

array([3, 9])

In [28]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
np.ones((2,3),dtype="int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
np.full((2,3), 99, dtype="int32")

array([[99, 99, 99],
       [99, 99, 99]])

In [31]:
np.full(arr3.shape, 99, dtype="int32")

array([[[99, 99],
        [99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99],
        [99, 99]]])

In [32]:
np.random.rand(2,3)

array([[0.00653241, 0.85381455, 0.15316973],
       [0.97490079, 0.52767629, 0.98678681]])

In [33]:
np.random.random_sample(arr.shape)

array([0.42875959, 0.30199143, 0.69673776, 0.46452829])

In [34]:
np.random.randint(1,10, size=(3,3))

array([[6, 2, 8],
       [1, 2, 3],
       [7, 7, 7]])

In [35]:
arr4 = np.array([[1,2,3]])
r1=np.repeat(arr4, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
output=np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
a = np.array((1,2,3))
b = a.copy()
b[1]=100
print(b)
print(a)

[  1 100   3]
[1 2 3]


In [39]:
a = np.array((1,2,3,4))
a+=2
print(a)

[3 4 5 6]


In [40]:
b = np.array([1,0,1,0])
c = a+b
print(c)

[4 4 6 6]


In [41]:
np.sin(c)


array([-0.7568025, -0.7568025, -0.2794155, -0.2794155])

In [42]:
a = np.ones((2,3))
print(a)
b = np.full((3,5), 2)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [43]:
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [44]:
a = np.array([[1,2,3],[4,5,6]])
print(np.min(a, axis=0))

[1 2 3]


In [45]:
np.max(a, axis=1)

array([3, 6])

In [46]:
np.sum(a, axis=1)

array([ 6, 15])

In [47]:
before = np.random.rand(2,3)
print(before.shape)
after = before.reshape(6,1)
print(after.shape)

(2, 3)
(6, 1)


In [48]:
v1 =  np.random.randint(1,10, size=(2,4))
v2 = np.random.randint(1,10, size=(2,4))
print(np.vstack([v1,v2,v2]))
print(np.hstack((v1,v2)))

[[7 9 4 7]
 [6 8 1 8]
 [7 7 5 3]
 [4 4 2 7]
 [7 7 5 3]
 [4 4 2 7]]
[[7 9 4 7 7 7 5 3]
 [6 8 1 8 4 4 2 7]]


In [49]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')

In [50]:
filedata>7

array([False, False, False, False, False, False, False,  True])

In [51]:
filedata[filedata>7]

array([8])

In [56]:
np.all(filedata>7, axis=0)

False

In [58]:
((filedata>1)&(filedata<8))

array([False,  True,  True,  True,  True,  True,  True, False])